python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/1.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/2.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/3.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/4.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/5.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/6.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/7.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/8.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/9.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/10.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/11.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/12.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/13.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/14.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/15.jpg
python3 run.py --model=mobilenet_thin --resize=432x368 --image=..Download/Dataset/True/16.jpg